using CommunityToolkit.Mvvm.ComponentModel;

namespace DiskMasterWinUI.Services;

public partial class LocalizationService : ObservableObject
{
    private static readonly Lazy<LocalizationService> _instance = new(() => new LocalizationService());
    public static LocalizationService Instance => _instance.Value;

    public event Action? LanguageChanged;

    [ObservableProperty]
    private string _currentLanguage = "zh-TW";

    public bool IsChinese => CurrentLanguage == "zh-TW" || CurrentLanguage == "zh-CN";

    public static string S(string zh, string en) => Instance.IsChinese ? zh : en;

    public static string T(string zhTw, string zhCn, string enUs, string jaJp) =>
        Instance.CurrentLanguage switch
        {
            "zh-TW" => zhTw,
            "zh-CN" => zhCn,
            "ja-JP" => jaJp,
            _ => enUs
        };

    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["zh-TW"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro 磁碟大師 — 旗艦級 Windows 磁碟維護與引導部署工具箱",
            ["EasyMode"] = "簡易模式",
            ["WimDeploy"] = "系統部署",
            ["BootManager"] = "引導管理",
            ["DiskTools"] = "磁碟工具",
            ["SystemRepair"] = "系統修復",
            ["NtfsPermissions"] = "權限管理",
            ["AdvancedMode"] = "進階腳本",
            ["Optimizer"] = "最佳化",
            ["Settings"] = "設定",
            ["Refresh"] = "重新整理",
            ["StatusReady"] = "就緒",
            ["AdminRequired"] = "未以系統管理員身分執行",
            ["AdminRequiredMsg"] = "DISM 映像修復、SFC 掃描、DiskPart 磁碟分區抹除等底層操作需要系統管理員權限才能執行。",
            ["RestartAdmin"] = "🚀 立即以管理員身分重啟",
            ["Disks"] = "實體磁碟",
            ["Volumes"] = "邏輯磁碟區",
            ["Partitions"] = "磁碟分割區",
            ["PartitionMap"] = "圖形化分割區地圖與容量調整",
            ["TargetSize"] = "目標容量",
            ["OperationDelta"] = "容量變更",
            ["CleanDisk"] = "清除磁碟",
            ["ConvertToGpt"] = "轉換為 GPT",
            ["ConvertToMbr"] = "轉換為 MBR",
            ["CreatePartition"] = "建立分割區",
            ["DeletePartition"] = "刪除分割區",
            ["FormatVolume"] = "格式化磁區",
            ["AssignLetter"] = "指派代號",
            ["ExecuteScript"] = "執行指令碼",
            ["OutputLog"] = "執行終端記錄",
            ["Clear"] = "清除記錄",
            ["Copy"] = "複製",
            ["ScanBootEntries"] = "掃描開機項目",
            ["BuildNewBoot"] = "全新分割區建置開機引導",
            ["ReadLicenseKeys"] = "讀取金鑰與序號",
            ["Win11Bypass"] = "繞過 Win11 硬體限制",
            ["CompactOs"] = "Compact OS 緊湊部署",
            ["AutoRepairBoot"] = "一鍵自動修復開機",
            ["WindowsUpdateRepair"] = "🔄 Windows Update 修復與更新管理",
            ["FixWuErrors"] = "🛠️ 一鍵修復 Windows Update 錯誤",
            ["ResetSoftwareDist"] = "📂 重建 SoftwareDistribution 資料夾",
            ["TriggerUpdateScan"] = "🔎 觸發更新偵測掃描",
            ["DisableWindowsUpdate"] = "停用 Windows Update 自動更新",
            ["DeepTempCleanup"] = "🧹 系統暫存與垃圾深度清理",
            ["ScanTemp"] = "🔍 掃描垃圾暫存",
            ["CleanSelectedTemp"] = "🧹 一鍵清理已勾選項目",
            ["RunCleanmgr"] = "🚀 深度清理 (Windows Cleanmgr)",
            ["FloatTab"] = "🪟 獨立浮動視窗",
            ["DockBack"] = "📥 嵌回主視窗",
            ["DockAll"] = "📥 全部嵌回主視窗",
            ["MoveFirst"] = "📌 移至最左側",
            ["MoveLast"] = "📌 移至最右側",
            ["OpenInExplorer"] = "📁 在檔案總管中開啟",
            ["CheckFilesystem"] = "🩺 執行 Chkdsk 檔案系統修復",
            ["DetailDisk"] = "🔍 磁碟硬體詳細規格",
            ["SmartCheck"] = "🩺 S.M.A.R.T. 健康檢查",
            ["CopySummary"] = "📋 複製摘要資訊",
            ["OpenDiskMgmt"] = "📂 開啟 Windows 磁碟管理",
            ["SaveLogAs"] = "💾 另存日誌文字檔",
            ["PasteLink"] = "📋 貼上剪貼簿直鏈",
            ["OpenMsPortal"] = "🌐 開啟微軟官網獲取直鏈",
            ["ProbeRange"] = "🔍 探測 HTTP Range 支援",
            ["ExportDiag"] = "📤 匯出系統除錯診斷日誌",
            ["PromptWindows"] = "🔔 彈出式視窗提示",
            ["TestPromptDialog"] = "🧪 測試提示視窗",
            ["CustomFonts"] = "🔤 自訂介面字型與排版",
            ["WorkspacePresets"] = "🗂️ 工作區佈局預設",
            ["WorkspaceMaster"] = "大師全功能",
            ["WorkspaceDeploy"] = "系統部署專精",
            ["WorkspaceRepair"] = "系統修復急救",
            ["WorkspaceGaming"] = "電競最佳化",
            ["WorkspaceLite"] = "極簡輕量模式",
            ["LanguageSelect"] = "🌐 介面語言與地區",
            ["Confirm"] = "確認",
            ["Cancel"] = "取消",
            ["Proceed"] = "繼續執行",
            ["WarningDestructive"] = "⚠️ 此操作將永久修改或抹除資料，請確認後再繼續！",
            ["TargetItem"] = "受影響對象:",
            ["Stop"] = "⏹️ 停止",
            ["DriverMgmtTitle"] = "OEM 驅動程式管理",
            ["DriverEnumBtn"] = "📋 列舉已安裝驅動",
            ["DriverBatchRemoveBtn"] = "🗑️ 批次移除已選驅動",
            ["DriverForceUninstall"] = "強制解除安裝 (/force)",
            ["DriverConfirmDelete"] = "確定要從系統中徹底刪除選取的 OEM 驅動程式嗎？",
            ["DriverDetailsTitle"] = "驅動程式詳細資訊",
            ["DriverClass"] = "裝置類別",
            ["DriverProvider"] = "提供商",
            ["DriverDate"] = "發布日期",
            ["DriverVersion"] = "版本號",
            ["DriverSigner"] = "數位簽章者",
            ["DriverSearchPlaceholder"] = "🔍 搜尋驅動 (INF 名稱、類別、提供商)...",
            ["StorageAnalyzerTitle"] = "系統目錄空間分析與百科",
            ["StorageScanBtn"] = "🔍 掃描系統目錄容量",
            ["StorageScanning"] = "正在計算目錄大小...",
            ["StorageSafetyRating"] = "安全等級",
            ["SafetySafeToPurge"] = "🟢 可安全清除",
            ["SafetyCleanViaTool"] = "🟡 建議透過系統工具 / DISM 清理",
            ["SafetyEssentialCore"] = "🔴 核心系統組件 - 請勿刪除",
            ["ActionOpenExplorer"] = "📁 在檔案總管中開啟",
            ["ActionSafeCleanup"] = "🧹 執行安全清理",
            ["ActionDismCleanup"] = "🛠️ 執行 DISM 元件庫清理",
            ["Dir_WinSxS_Title"] = "Windows 存案庫 (WinSxS)",
            ["Dir_WinSxS_Desc"] = "存放 Windows 元件備份與更新歷史版本。切勿手動刪除，否則將導致系統損毀！應使用 DISM 指令清理過期更新。",
            ["Dir_SoftwareDist_Title"] = "Windows Update 下載快取",
            ["Dir_SoftwareDist_Desc"] = "存放已下載的 Windows 更新暫存安裝包。更新出錯或卡死時，停止服務後可安全清空 DataStore 與 Download。",
            ["Dir_Installer_Title"] = "Windows Installer 快取",
            ["Dir_Installer_Desc"] = "存放已安裝程式的 .msi/.msp 安裝與反安裝修補包。手動誤刪會導致軟體無法更新或解除安裝。",
            ["Dir_DriverStore_Title"] = "驅動程式存放區",
            ["Dir_DriverStore_Desc"] = "存放所有第三方與內建驅動的備份檔案。舊版驅動可透過 pnputil 安全刪除。",
            ["Dir_Temp_Title"] = "系統與使用者暫存檔 (Temp)",
            ["Dir_Temp_Desc"] = "應用程式執行時建立的暫時檔案，可直接清空釋放空間。",
            ["Dir_AppData_Title"] = "應用程式資料夾 (AppData)",
            ["Dir_AppData_Desc"] = "存放軟體設定檔、快取與資料庫。Temp 與快取可清理，設定檔應保留。",
            ["Dir_SysVolInfo_Title"] = "系統還原與磁碟區資訊",
            ["Dir_SysVolInfo_Desc"] = "存放 NTFS 還原點與磁碟陰影複製 (VSS)。受 Windows 權限嚴格保護，可透過系統設定清除舊還原點。",
            ["Dir_Hiberfil_Title"] = "系統休眠映像檔 (hiberfil.sys)",
            ["Dir_Hiberfil_Desc"] = "供 Windows 休眠保存記憶體狀態。關閉休眠可徹底移除並釋放等同記憶體大小之空間。",
            ["Dir_Pagefile_Title"] = "虛擬記憶體分頁檔 (pagefile.sys)",
            ["Dir_Pagefile_Desc"] = "記憶體不足時的分頁置換空間。可透過系統設定調整大小，不可在運行時手動刪除。",
            ["Dir_WindowsBt_Title"] = "Windows 升級暫存檔 ($WINDOWS.~BT)",
            ["Dir_WindowsBt_Desc"] = "跨版本重大更新產生的暫存安裝檔案，升級成功後可安全清理。",
            ["Dir_WindowsOld_Title"] = "舊版 Windows 備份 (Windows.old)",
            ["Dir_WindowsOld_Desc"] = "升級後保留的舊系統備份。若系統穩定，可直接刪除釋放數十 GB。",
            ["SafeBootHeader"] = "MSConfig 安全開機設定",
            ["SafeBootNormal"] = "正常開機 (清除安全模式)",
            ["SafeBootMinimal"] = "最小安全模式 (Minimal)",
            ["SafeBootAlternateShell"] = "替代命令提示字元 (Alternate Shell)",
            ["SafeBootNetwork"] = "網路安全模式 (Network)",
            ["SafeBootDsRepair"] = "目錄服務修復 (DS Repair)",
            ["BootFlagsHeader"] = "進階開機旗標 (Boot Flags)",
            ["FlagNoGuiBoot"] = "無 GUI 開機 (noguiboot)",
            ["FlagBootLog"] = "開機記錄檔 (bootlog)",
            ["FlagBaseVideo"] = "基本視訊模式 (basevideo)",
            ["FlagSos"] = "顯示驅動載入資訊 (sos)",
            ["FlagTestSigning"] = "測試簽名模式 (testsigning)",
            ["FlagNoIntegrityChecks"] = "停用驅動簽章檢查",
            ["FlagHypervisor"] = "Hypervisor 虛擬化啟動",
            ["CpuTuningTitle"] = "處理器進階電源原則調校",
            ["UnhideBoostMode"] = "處理器效能激進提升模式 (Boost Mode)",
            ["UnhideEpp"] = "能源效能偏好 (EPP)",
            ["UnhideAutonomous"] = "處理器自主模式 (Autonomous Mode)",
            ["UnhideCoreParking"] = "CPU 核心停用原則 (Core Parking Min/Max)",
            ["UnhideHetero"] = "異質架構執行緒排程 (Intel P+E / AMD)",
            ["UnhideCooling"] = "系統散熱原則 (Active/Passive)",
            ["TweakDynamicTick"] = "停用動態計時週期 (disabledynamictick)",
            ["TweakLargeSystemCache"] = "啟用大型系統快取 (LargeSystemCache = 1)",
            ["TweakDisablePagingExec"] = "禁止內核分頁置換 (DisablePagingExecutive = 1)",
            ["PurgeHiberfilBtn"] = "🧹 徹底清除休眠檔並釋放空間",
            ["HiberfilReclaimedMsg"] = "已成功停用休眠並清空 hiberfil.sys，為 SSD 釋放 {0:F1} GB 空間！"
        },
        ["zh-CN"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro 磁盘大师 — 旗舰级 Windows 磁盘维护与引导部署工具箱",
            ["EasyMode"] = "简易模式",
            ["WimDeploy"] = "系统部署",
            ["BootManager"] = "引导管理",
            ["DiskTools"] = "磁盘工具",
            ["SystemRepair"] = "系统修复",
            ["NtfsPermissions"] = "权限管理",
            ["AdvancedMode"] = "高级脚本",
            ["Optimizer"] = "优化加速",
            ["Settings"] = "设置",
            ["Refresh"] = "刷新",
            ["StatusReady"] = "就绪",
            ["AdminRequired"] = "未以管理员身份运行",
            ["AdminRequiredMsg"] = "DISM 映像修复、SFC 扫描、DiskPart 磁盘分区清空等底层操作需要管理员权限才能运行。",
            ["RestartAdmin"] = "🚀 立即以管理员身份重启",
            ["Disks"] = "物理磁盘",
            ["Volumes"] = "逻辑卷",
            ["Partitions"] = "磁盘分区",
            ["PartitionMap"] = "图形化分区地图与容量调整",
            ["TargetSize"] = "目标容量",
            ["OperationDelta"] = "容量调整量",
            ["CleanDisk"] = "清空磁盘",
            ["ConvertToGpt"] = "转换为 GPT",
            ["ConvertToMbr"] = "转换为 MBR",
            ["CreatePartition"] = "创建分区",
            ["DeletePartition"] = "删除分区",
            ["FormatVolume"] = "格式化卷",
            ["AssignLetter"] = "分配盘符",
            ["ExecuteScript"] = "执行脚本",
            ["OutputLog"] = "终端输出记录",
            ["Clear"] = "清除记录",
            ["Copy"] = "复制",
            ["ScanBootEntries"] = "扫描引导项",
            ["BuildNewBoot"] = "全新分区重建引导",
            ["ReadLicenseKeys"] = "读取系统密钥与序列号",
            ["Win11Bypass"] = "绕过 Win11 硬件限制",
            ["CompactOs"] = "Compact OS 紧凑部署",
            ["AutoRepairBoot"] = "一键自动修复引导",
            ["WindowsUpdateRepair"] = "🔄 Windows Update 修复与更新管理",
            ["FixWuErrors"] = "🛠️ 一键修复 Windows Update 错误",
            ["ResetSoftwareDist"] = "📂 重建 SoftwareDistribution 文件夹",
            ["TriggerUpdateScan"] = "🔎 触发更新检测扫描",
            ["DisableWindowsUpdate"] = "禁用 Windows Update 自动更新",
            ["DeepTempCleanup"] = "🧹 系统缓存与垃圾深度清理",
            ["ScanTemp"] = "🔍 扫描垃圾缓存",
            ["CleanSelectedTemp"] = "🧹 一键清理选中项",
            ["RunCleanmgr"] = "🚀 深度清理 (Windows Cleanmgr)",
            ["FloatTab"] = "🪟 独立浮动窗口",
            ["DockBack"] = "📥 嵌回主窗口",
            ["DockAll"] = "📥 全部嵌回主窗口",
            ["MoveFirst"] = "📌 移至最左侧",
            ["MoveLast"] = "📌 移至最右侧",
            ["OpenInExplorer"] = "📁 在文件资源管理器中打开",
            ["CheckFilesystem"] = "🩺 运行 Chkdsk 文件系统修复",
            ["DetailDisk"] = "🔍 磁盘硬件详细规格",
            ["SmartCheck"] = "🩺 S.M.A.R.T. 健康检查",
            ["CopySummary"] = "📋 复制摘要信息",
            ["OpenDiskMgmt"] = "📂 打开 Windows 磁盘管理",
            ["SaveLogAs"] = "💾 另存日志文本文件",
            ["PasteLink"] = "📋 粘贴剪贴板直链",
            ["OpenMsPortal"] = "🌐 打开微软官网获取直链",
            ["ProbeRange"] = "🔍 探测 HTTP Range 支持",
            ["ExportDiag"] = "📤 导出系统调试诊断日志",
            ["PromptWindows"] = "🔔 弹出式窗口提示",
            ["TestPromptDialog"] = "🧪 测试提示窗口",
            ["CustomFonts"] = "🔤 自定义界面字体与排版",
            ["WorkspacePresets"] = "🗂️ 工作区布局预设",
            ["WorkspaceMaster"] = "大师全功能",
            ["WorkspaceDeploy"] = "系统部署专精",
            ["WorkspaceRepair"] = "系统修复急救",
            ["WorkspaceGaming"] = "电竞优化加速",
            ["WorkspaceLite"] = "极简轻量模式",
            ["LanguageSelect"] = "🌐 界面语言与地区",
            ["Confirm"] = "确认",
            ["Cancel"] = "取消",
            ["Proceed"] = "继续执行",
            ["WarningDestructive"] = "⚠️ 此操作将永久修改或清除数据，请确认后再继续！",
            ["TargetItem"] = "受影响对象:",
            ["Stop"] = "⏹️ 停止",
            ["DriverMgmtTitle"] = "OEM 驱动程序管理",
            ["DriverEnumBtn"] = "📋 列举已安装驱动",
            ["DriverBatchRemoveBtn"] = "🗑️ 批量移除所选驱动",
            ["DriverForceUninstall"] = "强制卸载 (/force)",
            ["DriverConfirmDelete"] = "确定要从系统中彻底删除选定的 OEM 驱动程序吗？",
            ["DriverDetailsTitle"] = "驱动程序详细信息",
            ["DriverClass"] = "设备类别",
            ["DriverProvider"] = "供应商",
            ["DriverDate"] = "发布日期",
            ["DriverVersion"] = "版本号",
            ["DriverSigner"] = "数字签名者",
            ["DriverSearchPlaceholder"] = "🔍 搜索驱动 (INF 名称、类别、提供商)...",
            ["StorageAnalyzerTitle"] = "系统目录空间分析与百科",
            ["StorageScanBtn"] = "🔍 扫描系统目录空间",
            ["StorageScanning"] = "正在计算目录大小...",
            ["StorageSafetyRating"] = "安全等级",
            ["SafetySafeToPurge"] = "🟢 可安全清理",
            ["SafetyCleanViaTool"] = "🟡 建议通过系统工具 / DISM 清理",
            ["SafetyEssentialCore"] = "🔴 核心系统组件 - 请勿删除",
            ["ActionOpenExplorer"] = "📁 在文件资源管理器中打开",
            ["ActionSafeCleanup"] = "🧹 执行安全清理",
            ["ActionDismCleanup"] = "🛠️ 执行 DISM 组件库清理",
            ["Dir_WinSxS_Title"] = "Windows 存案库 (WinSxS)",
            ["Dir_WinSxS_Desc"] = "存放 Windows 组件备份与更新历史版本。切勿手动删除，否则会导致系统损坏！应使用 DISM 命令清理过期更新。",
            ["Dir_SoftwareDist_Title"] = "Windows Update 下载缓存",
            ["Dir_SoftwareDist_Desc"] = "存放已下载的 Windows 更新暂存安装包。更新出错或卡死时，停止服务后可安全清空 DataStore 与 Download。",
            ["Dir_Installer_Title"] = "Windows Installer 缓存",
            ["Dir_Installer_Desc"] = "存放已安装程序的 .msi/.msp 安装与卸载补丁包。手动误删会导致软件无法更新或卸载。",
            ["Dir_DriverStore_Title"] = "驱动程序存放区",
            ["Dir_DriverStore_Desc"] = "存放所有第三方与内置驱动的备份文件。旧版驱动可通过 pnputil 安全删除。",
            ["Dir_Temp_Title"] = "系统与用户临时文件 (Temp)",
            ["Dir_Temp_Desc"] = "应用程序运行时创建的临时文件，可直接清空释放空间。",
            ["Dir_AppData_Title"] = "应用程序数据目录 (AppData)",
            ["Dir_AppData_Desc"] = "存放软件配置文件、缓存与数据库。Temp 与缓存可清理，配置文件应保留。",
            ["Dir_SysVolInfo_Title"] = "系统还原与卷信息",
            ["Dir_SysVolInfo_Desc"] = "存放 NTFS 还原点与卷影副本 (VSS)。受 Windows 权限保护，可通过系统设置清理旧还原点。",
            ["Dir_Hiberfil_Title"] = "系统休眠镜像文件 (hiberfil.sys)",
            ["Dir_Hiberfil_Desc"] = "供 Windows 休眠保存内存状态。关闭休眠可彻底移除并释放等同内存大小的空间。",
            ["Dir_Pagefile_Title"] = "虚拟内存分页文件 (pagefile.sys)",
            ["Dir_Pagefile_Desc"] = "内存不足时的分页置换空间。可通过系统设置调整大小，不可在运行时手动删除。",
            ["Dir_WindowsBt_Title"] = "Windows 升级暂存文件 ($WINDOWS.~BT)",
            ["Dir_WindowsBt_Desc"] = "跨版本重大更新产生的暂存安装文件，升级成功后可安全清理。",
            ["Dir_WindowsOld_Title"] = "旧版 Windows 备份 (Windows.old)",
            ["Dir_WindowsOld_Desc"] = "升级后保留的旧系统备份。若系统稳定，可直接删除释放数十 GB。",
            ["SafeBootHeader"] = "MSConfig 安全引导设置",
            ["SafeBootNormal"] = "正常启动 (清除安全模式)",
            ["SafeBootMinimal"] = "最小安全模式 (Minimal)",
            ["SafeBootAlternateShell"] = "替代命令提示符 (Alternate Shell)",
            ["SafeBootNetwork"] = "网络安全模式 (Network)",
            ["SafeBootDsRepair"] = "目录服务修复 (DS Repair)",
            ["BootFlagsHeader"] = "高级引导标志 (Boot Flags)",
            ["FlagNoGuiBoot"] = "无 GUI 引导 (noguiboot)",
            ["FlagBootLog"] = "引导日志 (bootlog)",
            ["FlagBaseVideo"] = "基本视频模式 (basevideo)",
            ["FlagSos"] = "显示驱动加载信息 (sos)",
            ["FlagTestSigning"] = "测试签名模式 (testsigning)",
            ["FlagNoIntegrityChecks"] = "禁用驱动签名检查",
            ["FlagHypervisor"] = "Hypervisor 虚拟化启动",
            ["CpuTuningTitle"] = "处理器高级电源策略调校",
            ["UnhideBoostMode"] = "处理器性能提升模式 (Boost Mode)",
            ["UnhideEpp"] = "能源效能偏好 (EPP)",
            ["UnhideAutonomous"] = "处理器自主模式 (Autonomous Mode)",
            ["UnhideCoreParking"] = "CPU 核心驻留策略 (Core Parking Min/Max)",
            ["UnhideHetero"] = "异构线程调度 (Intel P+E / AMD)",
            ["UnhideCooling"] = "系统散热策略 (Active/Passive)",
            ["TweakDynamicTick"] = "禁用动态计时器 (disabledynamictick)",
            ["TweakLargeSystemCache"] = "启用大型系统缓存 (LargeSystemCache = 1)",
            ["TweakDisablePagingExec"] = "禁止内核分页到磁盘 (DisablePagingExecutive = 1)",
            ["PurgeHiberfilBtn"] = "🧹 彻底清除休眠文件并释放空间",
            ["HiberfilReclaimedMsg"] = "已成功禁用休眠并清空 hiberfil.sys，为 SSD 释放 {0:F1} GB 空间！"
        },
        ["en-US"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro — Flagship Windows Disk Maintenance & Boot Deployment Suite",
            ["EasyMode"] = "Easy Mode",
            ["WimDeploy"] = "WIM Deploy",
            ["BootManager"] = "Boot Manager",
            ["DiskTools"] = "Disk Tools",
            ["SystemRepair"] = "System Repair",
            ["NtfsPermissions"] = "Permissions",
            ["AdvancedMode"] = "Advanced Scripts",
            ["Optimizer"] = "Optimizer",
            ["Settings"] = "Settings",
            ["Refresh"] = "Refresh",
            ["StatusReady"] = "Ready",
            ["AdminRequired"] = "Running with Non-Admin Privileges",
            ["AdminRequiredMsg"] = "DISM repair, SFC scan, DiskPart disk wiping and low-level disk actions require Administrator rights.",
            ["RestartAdmin"] = "🚀 Restart as Administrator",
            ["Disks"] = "Physical Disks",
            ["Volumes"] = "Volumes",
            ["Partitions"] = "Partitions",
            ["PartitionMap"] = "Graphical Partition Map & Sizer",
            ["TargetSize"] = "Target Size",
            ["OperationDelta"] = "Operation Delta",
            ["CleanDisk"] = "Clean Disk",
            ["ConvertToGpt"] = "Convert to GPT",
            ["ConvertToMbr"] = "Convert to MBR",
            ["CreatePartition"] = "Create Partition",
            ["DeletePartition"] = "Delete Partition",
            ["FormatVolume"] = "Format Volume",
            ["AssignLetter"] = "Assign Letter",
            ["ExecuteScript"] = "Execute Script",
            ["OutputLog"] = "Terminal Output Log",
            ["Clear"] = "Clear Log",
            ["Copy"] = "Copy",
            ["ScanBootEntries"] = "Scan Boot Entries",
            ["BuildNewBoot"] = "Build New Boot Manager",
            ["ReadLicenseKeys"] = "Read Keys & Serials",
            ["Win11Bypass"] = "Bypass Win11 Requirements",
            ["CompactOs"] = "Compact OS Deployment",
            ["AutoRepairBoot"] = "Auto Repair Boot",
            ["WindowsUpdateRepair"] = "🔄 Windows Update Repair & Management",
            ["FixWuErrors"] = "🛠️ 1-Click Fix Windows Update Errors",
            ["ResetSoftwareDist"] = "📂 Reset SoftwareDistribution Folder",
            ["TriggerUpdateScan"] = "🔎 Trigger Update Detection Scan",
            ["DisableWindowsUpdate"] = "Disable Windows Update Auto Updates",
            ["DeepTempCleanup"] = "🧹 System Temp & Deep Cache Cleanup",
            ["ScanTemp"] = "🔍 Scan Temp Files",
            ["CleanSelectedTemp"] = "🧹 Clean Selected Items",
            ["RunCleanmgr"] = "🚀 Deep Cleanup (Windows Cleanmgr)",
            ["FloatTab"] = "🪟 Float to Window",
            ["DockBack"] = "📥 Dock to Main Window",
            ["DockAll"] = "📥 Dock All Windows",
            ["MoveFirst"] = "📌 Move to First",
            ["MoveLast"] = "📌 Move to Last",
            ["OpenInExplorer"] = "📁 Open in File Explorer",
            ["CheckFilesystem"] = "🩺 Run Chkdsk Filesystem Repair",
            ["DetailDisk"] = "🔍 Detailed Hardware Specs",
            ["SmartCheck"] = "🩺 S.M.A.R.T. Health Check",
            ["CopySummary"] = "📋 Copy Summary Details",
            ["OpenDiskMgmt"] = "📂 Open Windows Disk Management",
            ["SaveLogAs"] = "💾 Save Log As Text File",
            ["PasteLink"] = "📋 Paste Direct Link from Clipboard",
            ["OpenMsPortal"] = "🌐 Open Microsoft Official Portal",
            ["ProbeRange"] = "🔍 Probe HTTP Range Support",
            ["ExportDiag"] = "📤 Export System Diagnostics Report",
            ["PromptWindows"] = "🔔 Enable Pop-up Prompt Windows",
            ["TestPromptDialog"] = "🧪 Test Prompt ContentDialog",
            ["CustomFonts"] = "🔤 Custom UI Fonts & Typography",
            ["WorkspacePresets"] = "🗂️ Workspace Layout Presets",
            ["WorkspaceMaster"] = "Full Master Suite",
            ["WorkspaceDeploy"] = "Deployment Focus",
            ["WorkspaceRepair"] = "System Repair Focus",
            ["WorkspaceGaming"] = "Gaming Optimizer Focus",
            ["WorkspaceLite"] = "Compact Lite Mode",
            ["LanguageSelect"] = "🌐 Language & Region",
            ["Confirm"] = "Confirm",
            ["Cancel"] = "Cancel",
            ["Proceed"] = "Proceed",
            ["WarningDestructive"] = "⚠️ This operation permanently modifies or erases data. Confirm to proceed!",
            ["TargetItem"] = "Target:",
            ["Stop"] = "⏹️ Stop",
            ["DriverMgmtTitle"] = "OEM Driver Management",
            ["DriverEnumBtn"] = "📋 Enumerate Installed Drivers",
            ["DriverBatchRemoveBtn"] = "🗑️ Batch Remove Selected",
            ["DriverForceUninstall"] = "Force Uninstall (/force)",
            ["DriverConfirmDelete"] = "Are you sure you want to permanently delete the selected OEM driver(s)?",
            ["DriverDetailsTitle"] = "Driver Details",
            ["DriverClass"] = "Device Class",
            ["DriverProvider"] = "Provider",
            ["DriverDate"] = "Driver Date",
            ["DriverVersion"] = "Version",
            ["DriverSigner"] = "Signer Name",
            ["DriverSearchPlaceholder"] = "🔍 Filter drivers (INF name, class, provider)...",
            ["StorageAnalyzerTitle"] = "Storage Directory Analyzer & Encyclopedia",
            ["StorageScanBtn"] = "🔍 Scan Directory Sizes",
            ["StorageScanning"] = "Calculating directory sizes...",
            ["StorageSafetyRating"] = "Safety Rating",
            ["SafetySafeToPurge"] = "🟢 Safe to Purge",
            ["SafetyCleanViaTool"] = "🟡 Clean via System Tool / DISM",
            ["SafetyEssentialCore"] = "🔴 Essential Core - Do Not Delete",
            ["ActionOpenExplorer"] = "📁 Open in File Explorer",
            ["ActionSafeCleanup"] = "🧹 Safe Cleanup",
            ["ActionDismCleanup"] = "🛠️ Run DISM Component Cleanup",
            ["Dir_WinSxS_Title"] = "Windows Component Store (WinSxS)",
            ["Dir_WinSxS_Desc"] = "Stores Windows component backups and updates. Do NOT manually delete or system will break. Use DISM Component Cleanup instead.",
            ["Dir_SoftwareDist_Title"] = "Windows Update Cache (SoftwareDistribution)",
            ["Dir_SoftwareDist_Desc"] = "Staged Windows Update installation packages. If updates are stuck or corrupt, safely flush DataStore & Download folders.",
            ["Dir_Installer_Title"] = "Windows Installer Cache ($SystemRoot$\\Installer)",
            ["Dir_Installer_Desc"] = "Contains .msi/.msp patch caches for installed apps. Manual deletion breaks application uninstallation and updates.",
            ["Dir_DriverStore_Title"] = "DriverStore Staged Repository",
            ["Dir_DriverStore_Desc"] = "Contains staged device drivers. Outdated driver packages can be safely purged using pnputil.",
            ["Dir_Temp_Title"] = "System & User Temp Files",
            ["Dir_Temp_Desc"] = "Temporary files generated during application execution. Safe to purge to reclaim space.",
            ["Dir_AppData_Title"] = "Application Data (AppData)",
            ["Dir_AppData_Desc"] = "Stores user application data and caches. Temp subdirectories are safe to purge.",
            ["Dir_SysVolInfo_Title"] = "System Volume Information",
            ["Dir_SysVolInfo_Desc"] = "Stores restore points and VSS volume shadow copies. Protected by Windows; clean via System Restore settings.",
            ["Dir_Hiberfil_Title"] = "Hibernation Memory Dump (hiberfil.sys)",
            ["Dir_Hiberfil_Desc"] = "Stores RAM state for hibernation and Fast Startup. Disabling hibernation purges this file instantly.",
            ["Dir_Pagefile_Title"] = "Paging File (pagefile.sys)",
            ["Dir_Pagefile_Desc"] = "Virtual memory swap file. Size can be configured in Advanced System Settings; cannot be deleted while in use.",
            ["Dir_WindowsBt_Title"] = "Windows Upgrade Staging ($WINDOWS.~BT)",
            ["Dir_WindowsBt_Desc"] = "Leftover files from feature updates. Safe to delete once upgrade is confirmed stable.",
            ["Dir_WindowsOld_Title"] = "Previous Windows Installation (Windows.old)",
            ["Dir_WindowsOld_Desc"] = "Backup of previous OS installation. If current installation is stable, safe to delete to reclaim tens of GBs.",
            ["SafeBootHeader"] = "Safe Boot Configuration",
            ["SafeBootNormal"] = "Normal Boot (Clear Safe Boot)",
            ["SafeBootMinimal"] = "Safe Boot: Minimal",
            ["SafeBootAlternateShell"] = "Safe Boot: Alternate Shell (Cmd)",
            ["SafeBootNetwork"] = "Safe Boot: Network",
            ["SafeBootDsRepair"] = "Safe Boot: Active Directory Repair",
            ["BootFlagsHeader"] = "Advanced Boot Flags",
            ["FlagNoGuiBoot"] = "No GUI Boot (noguiboot)",
            ["FlagBootLog"] = "Boot Log (bootlog)",
            ["FlagBaseVideo"] = "Base Video Mode (basevideo)",
            ["FlagSos"] = "OS Boot Info (sos)",
            ["FlagTestSigning"] = "Test Signing Mode (testsigning)",
            ["FlagNoIntegrityChecks"] = "Disable Driver Integrity Checks",
            ["FlagHypervisor"] = "Hypervisor Launch Type",
            ["CpuTuningTitle"] = "Processor Power Policy Tuning",
            ["UnhideBoostMode"] = "Processor Performance Boost Mode",
            ["UnhideEpp"] = "Energy Performance Preference (EPP)",
            ["UnhideAutonomous"] = "Processor Autonomous Mode",
            ["UnhideCoreParking"] = "CPU Core Parking Min/Max",
            ["UnhideHetero"] = "Heterogeneous Thread Scheduling",
            ["UnhideCooling"] = "System Cooling Policy",
            ["TweakDynamicTick"] = "Disable Dynamic Ticking",
            ["TweakLargeSystemCache"] = "Large System Cache",
            ["TweakDisablePagingExec"] = "Disable Paging Executive",
            ["PurgeHiberfilBtn"] = "🧹 Purge Hibernation File & Free SSD Space",
            ["HiberfilReclaimedMsg"] = "Hibernation disabled and hiberfil.sys purged. Reclaimed {0:F1} GB on SSD!"
        },
        ["ja-JP"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro — Windows ディスク管理・ブート修復スイート",
            ["EasyMode"] = "かんたんモード",
            ["WimDeploy"] = "システム展開",
            ["BootManager"] = "ブート管理",
            ["DiskTools"] = "ディスクツール",
            ["SystemRepair"] = "システム修復",
            ["NtfsPermissions"] = "権限管理",
            ["AdvancedMode"] = "高度スクリプト",
            ["Optimizer"] = "最適化",
            ["Settings"] = "設定",
            ["Refresh"] = "更新",
            ["StatusReady"] = "準備完了",
            ["AdminRequired"] = "管理者権限がありません",
            ["AdminRequiredMsg"] = "DISM 修復、SFC スキャン、DiskPart パーティション削除などの低レベル操作には管理者権限が必要です。",
            ["RestartAdmin"] = "🚀 管理者として再起動",
            ["Disks"] = "物理ディスク",
            ["Volumes"] = "論理ボリューム",
            ["Partitions"] = "ディスクパーティション",
            ["PartitionMap"] = "視覚的パーティションマップとサイズ変更",
            ["TargetSize"] = "目標サイズ",
            ["OperationDelta"] = "変更容量",
            ["CleanDisk"] = "ディスクをクリア",
            ["ConvertToGpt"] = "GPT に変換",
            ["ConvertToMbr"] = "MBR に変換",
            ["CreatePartition"] = "パーティション作成",
            ["DeletePartition"] = "パーティション削除",
            ["FormatVolume"] = "フォーマット",
            ["AssignLetter"] = "ドライブレター割当",
            ["ExecuteScript"] = "スクリプト実行",
            ["OutputLog"] = "実行ログ出力",
            ["Clear"] = "ログ消去",
            ["Copy"] = "コピー",
            ["ScanBootEntries"] = "ブート項目をスキャン",
            ["BuildNewBoot"] = "新規パーティションにブート再構築",
            ["ReadLicenseKeys"] = "プロダクトキーを読み取る",
            ["Win11Bypass"] = "Win11 ハードウェア制限を回避",
            ["CompactOs"] = "Compact OS コンパクト展開",
            ["AutoRepairBoot"] = "ワンクリック自動ブート修復",
            ["WindowsUpdateRepair"] = "🔄 Windows Update 修復と更新管理",
            ["FixWuErrors"] = "🛠️ Windows Update エラーを一括修復",
            ["ResetSoftwareDist"] = "📂 SoftwareDistribution フォルダ再構築",
            ["TriggerUpdateScan"] = "🔎 更新検出スキャンを開始",
            ["DisableWindowsUpdate"] = "Windows Update 自動更新を無効化",
            ["DeepTempCleanup"] = "🧹 システム一時ファイル・キャッシュ徹底削除",
            ["ScanTemp"] = "🔍 ゴミファイルをスキャン",
            ["CleanSelectedTemp"] = "🧹 選択項目をクリーンアップ",
            ["RunCleanmgr"] = "🚀 ディスクのクリーンアップ (Cleanmgr)",
            ["FloatTab"] = "🪟 独立ウィンドウとして分離",
            ["DockBack"] = "📥 メインウィンドウに戻す",
            ["DockAll"] = "📥 全ウィンドウを戻す",
            ["MoveFirst"] = "📌 先頭に移動",
            ["MoveLast"] = "📌 末尾に移動",
            ["OpenInExplorer"] = "📁 エクスプローラーで開く",
            ["CheckFilesystem"] = "🩺 Chkdsk ファイルシステム修復",
            ["DetailDisk"] = "🔍 ディスクハードウェア詳細",
            ["SmartCheck"] = "🩺 S.M.A.R.T. 健康診断",
            ["CopySummary"] = "📋 要約情報をコピー",
            ["OpenDiskMgmt"] = "📂 ディスクの管理を開く",
            ["SaveLogAs"] = "💾 ログをテキスト保存",
            ["PasteLink"] = "📋 クリップボード直リンクを貼り付け",
            ["OpenMsPortal"] = "🌐 マイクロソフト公式サイトを開く",
            ["ProbeRange"] = "🔍 HTTP Range サポートをテスト",
            ["ExportDiag"] = "📤 システム診断レポートを出力",
            ["PromptWindows"] = "🔔 ポップアップ通知ウィンドウを有効化",
            ["TestPromptDialog"] = "🧪 通知ダイアログをテスト",
            ["CustomFonts"] = "🔤 フォントとタイポグラフィのカスタマイズ",
            ["WorkspacePresets"] = "🗂️ ワークスペースプリセット",
            ["WorkspaceMaster"] = "マスターフル機能",
            ["WorkspaceDeploy"] = "システム展開特化",
            ["WorkspaceRepair"] = "システム修復特化",
            ["WorkspaceGaming"] = "ゲーム最適化特化",
            ["WorkspaceLite"] = "ミニマル軽量モード",
            ["LanguageSelect"] = "🌐 言語と地域",
            ["Confirm"] = "確認",
            ["Cancel"] = "キャンセル",
            ["Proceed"] = "続行",
            ["WarningDestructive"] = "⚠️ この操作はデータを永続的に変更または消去します。確認の上続行してください！",
            ["TargetItem"] = "対象:",
            ["Stop"] = "⏹️ 停止",
            ["DriverMgmtTitle"] = "OEM ドライバー管理",
            ["DriverEnumBtn"] = "📋 インストール済みドライバーを列挙",
            ["DriverBatchRemoveBtn"] = "🗑️ 選択したドライバーを一括削除",
            ["DriverForceUninstall"] = "強制アンインストール (/force)",
            ["DriverConfirmDelete"] = "選択した OEM ドライバーを完全に削除してもよろしいですか？",
            ["DriverDetailsTitle"] = "ドライバー詳細",
            ["DriverClass"] = "デバイスクラス",
            ["DriverProvider"] = "プロバイダー",
            ["DriverDate"] = "ドライバー日付",
            ["DriverVersion"] = "バージョン",
            ["DriverSigner"] = "デジタル署名",
            ["DriverSearchPlaceholder"] = "🔍 ドライバーを検索 (INF、クラス、提供元)...",
            ["StorageAnalyzerTitle"] = "システムディレクトリ容量分析と百科事典",
            ["StorageScanBtn"] = "🔍 ディレクトリ容量をスキャン",
            ["StorageScanning"] = "ディレクトリ容量を計算中...",
            ["StorageSafetyRating"] = "安全評価",
            ["SafetySafeToPurge"] = "🟢 安全に削除可能",
            ["SafetyCleanViaTool"] = "🟡 システムツールまたはDISMでクリーンアップ推奨",
            ["SafetyEssentialCore"] = "🔴 必須コアコンポーネント - 削除不可",
            ["ActionOpenExplorer"] = "📁 エクスプローラーで開く",
            ["ActionSafeCleanup"] = "🧹 安全クリーンアップ",
            ["ActionDismCleanup"] = "🛠️ DISM コンポーネントクリーンアップを実行",
            ["Dir_WinSxS_Title"] = "Windows コンポーネントストア (WinSxS)",
            ["Dir_WinSxS_Desc"] = "コンポーネントのバックアップや更新を保存。手動削除はシステム破損の原因となるため不可。DISMクリーンアップを使用してください。",
            ["Dir_SoftwareDist_Title"] = "Windows Update ダウンロードキャッシュ",
            ["Dir_SoftwareDist_Desc"] = "ダウンロードされた更新プログラムの一時保存場所。更新エラー時はサービス停止後に安全にクリアできます。",
            ["Dir_Installer_Title"] = "Windows インストーラー キャッシュ",
            ["Dir_Installer_Desc"] = "インストール済みアプリのパッチ。手動削除するとアプリのアンインストールや修復ができなくなります。",
            ["Dir_DriverStore_Title"] = "ドライバー ストア リポジトリ",
            ["Dir_DriverStore_Desc"] = "デバイスドライバーのバックアップ。不要な旧バージョンは pnputil で安全に削除可能です。",
            ["Dir_Temp_Title"] = "システム・ユーザー一時ファイル (Temp)",
            ["Dir_Temp_Desc"] = "アプリ実行時に作成される一時ファイル。直接クリアして空き容量を確保できます。",
            ["Dir_AppData_Title"] = "アプリケーションデータ (AppData)",
            ["Dir_AppData_Desc"] = "アプリの設定やキャッシュ。Temp サブフォルダは安全にクリア可能です。",
            ["Dir_SysVolInfo_Title"] = "システム ボリューム情報",
            ["Dir_SysVolInfo_Desc"] = "復元ポイントとVSSシャドウコピーを保存。システムの保護設定から古い復元ポイントを削除できます。",
            ["Dir_Hiberfil_Title"] = "休止状態メモリダンプ (hiberfil.sys)",
            ["Dir_Hiberfil_Desc"] = "休止状態や高速スタートアップ用。休止状態を無効化することで完全削除できます。",
            ["Dir_Pagefile_Title"] = "ページングファイル (pagefile.sys)",
            ["Dir_Pagefile_Desc"] = "仮想メモリのスワップ領域。システムの詳細設定からサイズを変更可能です。",
            ["Dir_WindowsBt_Title"] = "Windows アップグレード一時ファイル ($WINDOWS.~BT)",
            ["Dir_WindowsBt_Desc"] = "大型アップデート時の一時ファイル。アップグレード完了後は安全に削除可能です。",
            ["Dir_WindowsOld_Title"] = "以前の Windows インストール (Windows.old)",
            ["Dir_WindowsOld_Desc"] = "アップグレード前のOSバックアップ。動作が安定している場合は削除して数十GBを解放できます。",
            ["SafeBootHeader"] = "セーフブート設定",
            ["SafeBootNormal"] = "通常起動 (セーフモード解除)",
            ["SafeBootMinimal"] = "最小セーフモード (Minimal)",
            ["SafeBootAlternateShell"] = "代替シェル (コマンドプロンプト)",
            ["SafeBootNetwork"] = "ネットワーク対応セーフモード",
            ["SafeBootDsRepair"] = "ディレクトリサービス修復",
            ["BootFlagsHeader"] = "高度ブートフラグ",
            ["FlagNoGuiBoot"] = "GUIブート無効 (noguiboot)",
            ["FlagBootLog"] = "ブートログ (bootlog)",
            ["FlagBaseVideo"] = "基本ビデオ (basevideo)",
            ["FlagSos"] = "ドライバ読込情報 (sos)",
            ["FlagTestSigning"] = "テスト署名 (testsigning)",
            ["FlagNoIntegrityChecks"] = "ドライバ署名検証無効",
            ["FlagHypervisor"] = "Hypervisor 起動",
            ["CpuTuningTitle"] = "プロセッサ詳細電源ポリシー調整",
            ["UnhideBoostMode"] = "プロセッサパフォーマンス向上モード",
            ["UnhideEpp"] = "エネルギー パフォーマンス設定 (EPP)",
            ["UnhideAutonomous"] = "プロセッサ自律モード",
            ["UnhideCoreParking"] = "CPU コア パーキング設定",
            ["UnhideHetero"] = "異種アーキテクチャ スケジューリング",
            ["UnhideCooling"] = "システム冷却ポリシー",
            ["TweakDynamicTick"] = "動的ティックの無効化",
            ["TweakLargeSystemCache"] = "ラージ システム キャッシュ",
            ["TweakDisablePagingExec"] = "ページング エグゼクティブの無効化",
            ["PurgeHiberfilBtn"] = "🧹 休止ファイルを消去して SSD を解放",
            ["HiberfilReclaimedMsg"] = "休止状態を無効化し hiberfil.sys を消去しました。SSD 上で {0:F1} GB を解放しました！"
        }
    };

    public string this[string key] => GetString(key);

    public string GetString(string key)
    {
        if (_translations.TryGetValue(CurrentLanguage, out var langDict) && langDict.TryGetValue(key, out var val))
        {
            return val;
        }

        if (_translations["zh-TW"].TryGetValue(key, out var twVal))
        {
            return twVal;
        }

        if (_translations["en-US"].TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }

    public void SetLanguage(string language)
    {
        CurrentLanguage = language;
    }

    public void ToggleLanguage()
    {
        CurrentLanguage = CurrentLanguage switch
        {
            "zh-TW" => "zh-CN",
            "zh-CN" => "en-US",
            "en-US" => "ja-JP",
            _ => "zh-TW"
        };
    }

    partial void OnCurrentLanguageChanged(string value)
    {
        LanguageChanged?.Invoke();
        OnPropertyChanged(string.Empty);
    }
}
