using CommunityToolkit.Mvvm.ComponentModel;

namespace DiskMasterWinUI.Services;

public partial class LocalizationService : ObservableObject
{
    private static readonly Lazy<LocalizationService> _instance = new(() => new LocalizationService());
    public static LocalizationService Instance => _instance.Value;

    public event Action? LanguageChanged;

    [ObservableProperty]
    private string _currentLanguage = "zh-TW";

    public bool IsChinese => CurrentLanguage == "zh-TW" || CurrentLanguage == "zh-CN";

    public static string S(string zh, string en) => Instance.IsChinese ? zh : en;

    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["zh-TW"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro 磁碟大師 — 旗艦級 Windows 磁碟維護與引導部署工具箱",
            ["EasyMode"] = "簡易模式",
            ["WimDeploy"] = "系統部署",
            ["BootManager"] = "引導管理",
            ["DiskTools"] = "磁碟工具",
            ["SystemRepair"] = "系統修復",
            ["NtfsPermissions"] = "權限管理",
            ["AdvancedMode"] = "進階腳本",
            ["Optimizer"] = "最佳化",
            ["Settings"] = "設定",
            ["Refresh"] = "重新整理",
            ["StatusReady"] = "就緒",
            ["AdminRequired"] = "未以系統管理員身分執行",
            ["AdminRequiredMsg"] = "DISM 映像修復、SFC 掃描、DiskPart 磁碟分區抹除等底層操作需要系統管理員權限才能執行。",
            ["RestartAdmin"] = "🚀 立即以管理員身分重啟",
            ["Disks"] = "實體磁碟",
            ["Volumes"] = "邏輯磁碟區",
            ["Partitions"] = "磁碟分割區",
            ["PartitionMap"] = "圖形化分割區地圖與容量調整",
            ["TargetSize"] = "目標容量",
            ["OperationDelta"] = "容量變更",
            ["CleanDisk"] = "清除磁碟",
            ["ConvertToGpt"] = "轉換為 GPT",
            ["ConvertToMbr"] = "轉換為 MBR",
            ["CreatePartition"] = "建立分割區",
            ["DeletePartition"] = "刪除分割區",
            ["FormatVolume"] = "格式化磁區",
            ["AssignLetter"] = "指派代號",
            ["ExecuteScript"] = "執行指令碼",
            ["OutputLog"] = "執行終端記錄",
            ["Clear"] = "清除記錄",
            ["Copy"] = "複製",
            ["ScanBootEntries"] = "掃描開機項目",
            ["BuildNewBoot"] = "全新分割區建置開機引導",
            ["ReadLicenseKeys"] = "讀取金鑰與序號",
            ["Win11Bypass"] = "繞過 Win11 硬體限制",
            ["CompactOs"] = "Compact OS 緊湊部署",
            ["AutoRepairBoot"] = "一鍵自動修復開機",
            ["WindowsUpdateRepair"] = "🔄 Windows Update 修復與更新管理",
            ["FixWuErrors"] = "🛠️ 一鍵修復 Windows Update 錯誤",
            ["ResetSoftwareDist"] = "📂 重建 SoftwareDistribution 資料夾",
            ["TriggerUpdateScan"] = "🔎 觸發更新偵測掃描",
            ["DisableWindowsUpdate"] = "停用 Windows Update 自動更新",
            ["DeepTempCleanup"] = "🧹 系統暫存與垃圾深度清理",
            ["ScanTemp"] = "🔍 掃描垃圾暫存",
            ["CleanSelectedTemp"] = "🧹 一鍵清理已勾選項目",
            ["RunCleanmgr"] = "🚀 深度清理 (Windows Cleanmgr)",
            ["FloatTab"] = "🪟 獨立浮動視窗",
            ["DockBack"] = "📥 嵌回主視窗",
            ["DockAll"] = "📥 全部嵌回主視窗",
            ["MoveFirst"] = "📌 移至最左側",
            ["MoveLast"] = "📌 移至最右側",
            ["OpenInExplorer"] = "📁 在檔案總管中開啟",
            ["CheckFilesystem"] = "🩺 執行 Chkdsk 檔案系統修復",
            ["DetailDisk"] = "🔍 磁碟硬體詳細規格",
            ["SmartCheck"] = "🩺 S.M.A.R.T. 健康檢查",
            ["CopySummary"] = "📋 複製摘要資訊",
            ["OpenDiskMgmt"] = "📂 開啟 Windows 磁碟管理",
            ["SaveLogAs"] = "💾 另存日誌文字檔",
            ["PasteLink"] = "📋 貼上剪貼簿直鏈",
            ["OpenMsPortal"] = "🌐 開啟微軟官網獲取直鏈",
            ["ProbeRange"] = "🔍 探測 HTTP Range 支援",
            ["ExportDiag"] = "📤 匯出系統除錯診斷日誌",
            ["PromptWindows"] = "🔔 彈出式視窗提示",
            ["TestPromptDialog"] = "🧪 測試提示視窗",
            ["CustomFonts"] = "🔤 自訂介面字型與排版",
            ["WorkspacePresets"] = "🗂️ 工作區佈局預設",
            ["WorkspaceMaster"] = "大師全功能",
            ["WorkspaceDeploy"] = "系統部署專精",
            ["WorkspaceRepair"] = "系統修復急救",
            ["WorkspaceGaming"] = "電競最佳化",
            ["WorkspaceLite"] = "極簡輕量模式",
            ["LanguageSelect"] = "🌐 介面語言與地區"
        },
        ["zh-CN"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro 磁盘大师 — 旗舰级 Windows 磁盘维护与引导部署工具箱",
            ["EasyMode"] = "简易模式",
            ["WimDeploy"] = "系统部署",
            ["BootManager"] = "引导管理",
            ["DiskTools"] = "磁盘工具",
            ["SystemRepair"] = "系统修复",
            ["NtfsPermissions"] = "权限管理",
            ["AdvancedMode"] = "高级脚本",
            ["Optimizer"] = "优化加速",
            ["Settings"] = "设置",
            ["Refresh"] = "刷新",
            ["StatusReady"] = "就绪",
            ["AdminRequired"] = "未以管理员身份运行",
            ["AdminRequiredMsg"] = "DISM 映像修复、SFC 扫描、DiskPart 磁盘分区清空等底层操作需要管理员权限才能运行。",
            ["RestartAdmin"] = "🚀 立即以管理员身份重启",
            ["Disks"] = "物理磁盘",
            ["Volumes"] = "逻辑卷",
            ["Partitions"] = "磁盘分区",
            ["PartitionMap"] = "图形化分区地图与容量调整",
            ["TargetSize"] = "目标容量",
            ["OperationDelta"] = "容量调整量",
            ["CleanDisk"] = "清空磁盘",
            ["ConvertToGpt"] = "转换为 GPT",
            ["ConvertToMbr"] = "转换为 MBR",
            ["CreatePartition"] = "创建分区",
            ["DeletePartition"] = "删除分区",
            ["FormatVolume"] = "格式化卷",
            ["AssignLetter"] = "分配盘符",
            ["ExecuteScript"] = "执行脚本",
            ["OutputLog"] = "终端输出记录",
            ["Clear"] = "清除记录",
            ["Copy"] = "复制",
            ["ScanBootEntries"] = "扫描引导项",
            ["BuildNewBoot"] = "全新分区重建引导",
            ["ReadLicenseKeys"] = "读取系统密钥与序列号",
            ["Win11Bypass"] = "绕过 Win11 硬件限制",
            ["CompactOs"] = "Compact OS 紧凑部署",
            ["AutoRepairBoot"] = "一键自动修复引导",
            ["WindowsUpdateRepair"] = "🔄 Windows Update 修复与更新管理",
            ["FixWuErrors"] = "🛠️ 一键修复 Windows Update 错误",
            ["ResetSoftwareDist"] = "📂 重建 SoftwareDistribution 文件夹",
            ["TriggerUpdateScan"] = "🔎 触发更新检测扫描",
            ["DisableWindowsUpdate"] = "禁用 Windows Update 自动更新",
            ["DeepTempCleanup"] = "🧹 系统缓存与垃圾深度清理",
            ["ScanTemp"] = "🔍 扫描垃圾缓存",
            ["CleanSelectedTemp"] = "🧹 一键清理选中项",
            ["RunCleanmgr"] = "🚀 深度清理 (Windows Cleanmgr)",
            ["FloatTab"] = "🪟 独立浮动窗口",
            ["DockBack"] = "📥 嵌回主窗口",
            ["DockAll"] = "📥 全部嵌回主窗口",
            ["MoveFirst"] = "📌 移至最左侧",
            ["MoveLast"] = "📌 移至最右侧",
            ["OpenInExplorer"] = "📁 在文件资源管理器中打开",
            ["CheckFilesystem"] = "🩺 运行 Chkdsk 文件系统修复",
            ["DetailDisk"] = "🔍 磁盘硬件详细规格",
            ["SmartCheck"] = "🩺 S.M.A.R.T. 健康检查",
            ["CopySummary"] = "📋 复制摘要信息",
            ["OpenDiskMgmt"] = "📂 打开 Windows 磁盘管理",
            ["SaveLogAs"] = "💾 另存日志文本文件",
            ["PasteLink"] = "📋 粘贴剪贴板直链",
            ["OpenMsPortal"] = "🌐 打开微软官网获取直链",
            ["ProbeRange"] = "🔍 探测 HTTP Range 支持",
            ["ExportDiag"] = "📤 导出系统调试诊断日志",
            ["PromptWindows"] = "🔔 弹出式窗口提示",
            ["TestPromptDialog"] = "🧪 测试提示窗口",
            ["CustomFonts"] = "🔤 自定义界面字体与排版",
            ["WorkspacePresets"] = "🗂️ 工作区布局预设",
            ["WorkspaceMaster"] = "大师全功能",
            ["WorkspaceDeploy"] = "系统部署专精",
            ["WorkspaceRepair"] = "系统修复急救",
            ["WorkspaceGaming"] = "电竞优化加速",
            ["WorkspaceLite"] = "极简轻量模式",
            ["LanguageSelect"] = "🌐 界面语言与地区"
        },
        ["en-US"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro — Flagship Windows Disk Maintenance & Boot Deployment Suite",
            ["EasyMode"] = "Easy Mode",
            ["WimDeploy"] = "WIM Deploy",
            ["BootManager"] = "Boot Manager",
            ["DiskTools"] = "Disk Tools",
            ["SystemRepair"] = "System Repair",
            ["NtfsPermissions"] = "Permissions",
            ["AdvancedMode"] = "Advanced Scripts",
            ["Optimizer"] = "Optimizer",
            ["Settings"] = "Settings",
            ["Refresh"] = "Refresh",
            ["StatusReady"] = "Ready",
            ["AdminRequired"] = "Running with Non-Admin Privileges",
            ["AdminRequiredMsg"] = "DISM repair, SFC scan, DiskPart disk wiping and low-level disk actions require Administrator rights.",
            ["RestartAdmin"] = "🚀 Restart as Administrator",
            ["Disks"] = "Physical Disks",
            ["Volumes"] = "Volumes",
            ["Partitions"] = "Partitions",
            ["PartitionMap"] = "Graphical Partition Map & Sizer",
            ["TargetSize"] = "Target Size",
            ["OperationDelta"] = "Operation Delta",
            ["CleanDisk"] = "Clean Disk",
            ["ConvertToGpt"] = "Convert to GPT",
            ["ConvertToMbr"] = "Convert to MBR",
            ["CreatePartition"] = "Create Partition",
            ["DeletePartition"] = "Delete Partition",
            ["FormatVolume"] = "Format Volume",
            ["AssignLetter"] = "Assign Letter",
            ["ExecuteScript"] = "Execute Script",
            ["OutputLog"] = "Terminal Output Log",
            ["Clear"] = "Clear Log",
            ["Copy"] = "Copy",
            ["ScanBootEntries"] = "Scan Boot Entries",
            ["BuildNewBoot"] = "Build New Boot Manager",
            ["ReadLicenseKeys"] = "Read Keys & Serials",
            ["Win11Bypass"] = "Bypass Win11 Requirements",
            ["CompactOs"] = "Compact OS Deployment",
            ["AutoRepairBoot"] = "Auto Repair Boot",
            ["WindowsUpdateRepair"] = "🔄 Windows Update Repair & Management",
            ["FixWuErrors"] = "🛠️ 1-Click Fix Windows Update Errors",
            ["ResetSoftwareDist"] = "📂 Reset SoftwareDistribution Folder",
            ["TriggerUpdateScan"] = "🔎 Trigger Update Detection Scan",
            ["DisableWindowsUpdate"] = "Disable Windows Update Auto Updates",
            ["DeepTempCleanup"] = "🧹 System Temp & Deep Cache Cleanup",
            ["ScanTemp"] = "🔍 Scan Temp Files",
            ["CleanSelectedTemp"] = "🧹 Clean Selected Items",
            ["RunCleanmgr"] = "🚀 Deep Cleanup (Windows Cleanmgr)",
            ["FloatTab"] = "🪟 Float to Window",
            ["DockBack"] = "📥 Dock to Main Window",
            ["DockAll"] = "📥 Dock All Windows",
            ["MoveFirst"] = "📌 Move to First",
            ["MoveLast"] = "📌 Move to Last",
            ["OpenInExplorer"] = "📁 Open in File Explorer",
            ["CheckFilesystem"] = "🩺 Run Chkdsk Filesystem Repair",
            ["DetailDisk"] = "🔍 Detailed Hardware Specs",
            ["SmartCheck"] = "🩺 S.M.A.R.T. Health Check",
            ["CopySummary"] = "📋 Copy Summary Details",
            ["OpenDiskMgmt"] = "📂 Open Windows Disk Management",
            ["SaveLogAs"] = "💾 Save Log As Text File",
            ["PasteLink"] = "📋 Paste Direct Link from Clipboard",
            ["OpenMsPortal"] = "🌐 Open Microsoft Official Portal",
            ["ProbeRange"] = "🔍 Probe HTTP Range Support",
            ["ExportDiag"] = "📤 Export System Diagnostics Report",
            ["PromptWindows"] = "🔔 Enable Pop-up Prompt Windows",
            ["TestPromptDialog"] = "🧪 Test Prompt ContentDialog",
            ["CustomFonts"] = "🔤 Custom UI Fonts & Typography",
            ["WorkspacePresets"] = "🗂️ Workspace Layout Presets",
            ["WorkspaceMaster"] = "Full Master Suite",
            ["WorkspaceDeploy"] = "Deployment Focus",
            ["WorkspaceRepair"] = "System Repair Focus",
            ["WorkspaceGaming"] = "Gaming Optimizer Focus",
            ["WorkspaceLite"] = "Compact Lite Mode",
            ["LanguageSelect"] = "🌐 Language & Region"
        },
        ["ja-JP"] = new()
        {
            ["AppTitle"] = "DiskMaster Pro — Windows ディスク管理・ブート修復スイート",
            ["EasyMode"] = "かんたんモード",
            ["WimDeploy"] = "システム展開",
            ["BootManager"] = "ブート管理",
            ["DiskTools"] = "ディスクツール",
            ["SystemRepair"] = "システム修復",
            ["NtfsPermissions"] = "権限管理",
            ["AdvancedMode"] = "高度スクリプト",
            ["Optimizer"] = "最適化",
            ["Settings"] = "設定",
            ["Refresh"] = "更新",
            ["StatusReady"] = "準備完了",
            ["AdminRequired"] = "管理者権限がありません",
            ["AdminRequiredMsg"] = "DISM 修復、SFC スキャン、DiskPart パーティション削除などの低レベル操作には管理者権限が必要です。",
            ["RestartAdmin"] = "🚀 管理者として再起動",
            ["Disks"] = "物理ディスク",
            ["Volumes"] = "論理ボリューム",
            ["Partitions"] = "ディスクパーティション",
            ["PartitionMap"] = "視覚的パーティションマップとサイズ変更",
            ["TargetSize"] = "目標サイズ",
            ["OperationDelta"] = "変更容量",
            ["CleanDisk"] = "ディスクをクリア",
            ["ConvertToGpt"] = "GPT に変換",
            ["ConvertToMbr"] = "MBR に変換",
            ["CreatePartition"] = "パーティション作成",
            ["DeletePartition"] = "パーティション削除",
            ["FormatVolume"] = "フォーマット",
            ["AssignLetter"] = "ドライブレター割当",
            ["ExecuteScript"] = "スクリプト実行",
            ["OutputLog"] = "実行ログ出力",
            ["Clear"] = "ログ消去",
            ["Copy"] = "コピー",
            ["ScanBootEntries"] = "ブート項目をスキャン",
            ["BuildNewBoot"] = "新規パーティションにブート再構築",
            ["ReadLicenseKeys"] = "プロダクトキーを読み取る",
            ["Win11Bypass"] = "Win11 ハードウェア制限を回避",
            ["CompactOs"] = "Compact OS コンパクト展開",
            ["AutoRepairBoot"] = "ワンクリック自動ブート修復",
            ["WindowsUpdateRepair"] = "🔄 Windows Update 修復と更新管理",
            ["FixWuErrors"] = "🛠️ Windows Update エラーを一括修復",
            ["ResetSoftwareDist"] = "📂 SoftwareDistribution フォルダ再構築",
            ["TriggerUpdateScan"] = "🔎 更新検出スキャンを開始",
            ["DisableWindowsUpdate"] = "Windows Update 自動更新を無効化",
            ["DeepTempCleanup"] = "🧹 システム一時ファイル・キャッシュ徹底削除",
            ["ScanTemp"] = "🔍 ゴミファイルをスキャン",
            ["CleanSelectedTemp"] = "🧹 選択項目をクリーンアップ",
            ["RunCleanmgr"] = "🚀 ディスクのクリーンアップ (Cleanmgr)",
            ["FloatTab"] = "🪟 独立ウィンドウとして分離",
            ["DockBack"] = "📥 メインウィンドウに戻す",
            ["DockAll"] = "📥 全ウィンドウを戻す",
            ["MoveFirst"] = "📌 先頭に移動",
            ["MoveLast"] = "📌 末尾に移動",
            ["OpenInExplorer"] = "📁 エクスプローラーで開く",
            ["CheckFilesystem"] = "🩺 Chkdsk ファイルシステム修復",
            ["DetailDisk"] = "🔍 ディスクハードウェア詳細",
            ["SmartCheck"] = "🩺 S.M.A.R.T. 健康診断",
            ["CopySummary"] = "📋 要約情報をコピー",
            ["OpenDiskMgmt"] = "📂 ディスクの管理を開く",
            ["SaveLogAs"] = "💾 ログをテキスト保存",
            ["PasteLink"] = "📋 クリップボード直リンクを貼り付け",
            ["OpenMsPortal"] = "🌐 マイクロソフト公式サイトを開く",
            ["ProbeRange"] = "🔍 HTTP Range サポートをテスト",
            ["ExportDiag"] = "📤 システム診断レポートを出力",
            ["PromptWindows"] = "🔔 ポップアップ通知ウィンドウを有効化",
            ["TestPromptDialog"] = "🧪 通知ダイアログをテスト",
            ["CustomFonts"] = "🔤 フォントとタイポグラフィのカスタマイズ",
            ["WorkspacePresets"] = "🗂️ ワークスペースプリセット",
            ["WorkspaceMaster"] = "マスターフル機能",
            ["WorkspaceDeploy"] = "システム展開特化",
            ["WorkspaceRepair"] = "システム修復特化",
            ["WorkspaceGaming"] = "ゲーム最適化特化",
            ["WorkspaceLite"] = "ミニマル軽量モード",
            ["LanguageSelect"] = "🌐 言語と地域"
        }
    };

    public string this[string key] => GetString(key);

    public string GetString(string key)
    {
        if (_translations.TryGetValue(CurrentLanguage, out var langDict) && langDict.TryGetValue(key, out var val))
        {
            return val;
        }

        if (_translations["zh-TW"].TryGetValue(key, out var twVal))
        {
            return twVal;
        }

        if (_translations["en-US"].TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }

    public void ToggleLanguage()
    {
        CurrentLanguage = CurrentLanguage switch
        {
            "zh-TW" => "zh-CN",
            "zh-CN" => "en-US",
            "en-US" => "ja-JP",
            _ => "zh-TW"
        };
    }

    partial void OnCurrentLanguageChanged(string value)
    {
        LanguageChanged?.Invoke();
        OnPropertyChanged(string.Empty);
    }
}
